import { Client, Message } from 'discord.js'

//sends a bad joke into chat
export default (message: Message, _client: Client) => {
  let genre = message.content.split(' ').slice(1, undefined).join()
  let size = 1;
  let dict;

  switch(genre) {
    case "math":
      // code block
      dict = dict_math;
      size = 92;
      break;
    default: //dad joke or something
      dict = dict_standard;
      size = 144; //don't forget to update this
      //code block
  }

  let index = getRandomIndex(size);
  let joke = dict[index];
  message.channel.send(joke);
}

function getRandomIndex(max: number) {
  return Math.floor(Math.random() * max);
  //https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random
}


//ignore everything below here plz
var dict_standard = [
  "I'm afraid for the calendar. Its days are numbered.",
  "My wife said I should do lunges to stay in shape. That would be a big step forward.",
  "Why do fathers take an extra pair of socks when they go golfing? In case they get a hole in one!",
  "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
  "What do a tick and the Eiffel Tower have in common? They're both Paris sites.",
  "What do you call a fish wearing a bowtie? Sofishticated.",
  "How do you follow Will Smith in the snow? You follow the fresh prints.",
  "If April showers bring May flowers, what do May flowers bring? Pilgrims.",
  "I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "Dear Math, grow up and solve your own problems.",
  "What did the janitor say when he jumped out of the closet? Supplies!",
  "Have you heard about the chocolate record player? It sounds pretty sweet.",
  "What did the ocean say to the beach? Nothing, it just waved.",
  "Why do seagulls fly over the ocean? Because if they flew over the bay, we'd call them bagels.",
  "I only know 25 letters of the alphabet. I don't know y.",
  "How does the moon cut his hair? Eclipse it.",
  "What did one wall say to the other? I'll meet you at the corner.",
  "What did the zero say to the eight? That belt looks good on you.",
  "A skeleton walks into a bar and says, 'Hey, bartender. I'll have one beer and a mop.'",
  "Where do fruits go on vacation? Pear-is!",
  "I asked my dog what's two minus two. He said nothing.",
  "What did Baby Corn say to Mama Corn? Where's Pop Corn?",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
  "What does a sprinter eat before a race? Nothing, they fast!",
  "Where do you learn to make a banana split? Sundae school.",
  "What has more letters than the alphabet? The post office!",
  "Dad, did you get a haircut? No, I got them all cut!",
  "What do you call a poor Santa Claus? St. Nickel-less.",
  "I got carded at a liquor store, and my Blockbuster card accidentally fell out. The cashier said never mind.",
  "Where do boats go when they're sick? To the boat doc.",
  "I don't trust those trees. They seem kind of shady.",
  "My wife is really mad at the fact that I have no sense of direction. So I packed up my stuff and right!",
  "How do you get a squirrel to like you? Act like a nut.",
  "Why don't eggs tell jokes? They'd crack each other up.",
  "I don't trust stairs. They're always up to something.",
  "What do you call someone with no body and no nose? Nobody knows.",
  "Did you hear the rumor about butter? Well, I'm not going to spread it!",
  "Why couldn't the bicycle stand up by itself? It was two tired.",
  "What did one hat say to the other? Stay here! I'm going on ahead.",
  "Why did Billy get fired from the banana factory? He kept throwing away the bent ones.",
  "Dad, can you put my shoes on? No, I don't think they'll fit me.",
  "Why can't a nose be 12 inches long? Because then it would be a foot.",
  "What does a lemon say when it answers the phone? Yellow!",
  "This graveyard looks overcrowded. People must be dying to get in.",
  "What kind of car does an egg drive? A yolkswagen.",
  "Dad, can you put the cat out? I didn't know it was on fire.",
  "How do you make 7 even? Take away the s.",
  "How does a taco say grace? Lettuce pray.",
  "What time did the man go to the dentist? Tooth hurt-y.",
  "Why didn't the skeleton climb the mountain? It didn't have the guts.",
  "What do you call it when a snowman throws a tantrum? A meltdown.",
  "How many tickles does it take to make an octopus laugh? Ten tickles.",
  "I have a joke about chemistry, but I don't think it will get a reaction.",
  "What concert costs just 45 cents? 50 Cent featuring Nickelback!",
  "What does a bee use to brush its hair? A honeycomb!",
  "How do you make a tissue dance? You put a little boogie in it.",
  "Why did the math book look so sad? Because of all of its problems!",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "My dad told me a joke about boxing. I guess I missed the punch line.",
  "What kind of shoes do ninjas wear? Sneakers!",
  "How does a penguin build its house? Igloos it together.",
  "How did Harry Potter get down the hill? Walking. JK! Rowling.",
  "I used to be addicted to soap, but I'm clean now.",
  "A guy walks into a bar...and he was disqualified from the limbo contest.",
  "You think swimming with sharks is expensive? Swimming with sharks cost me an arm and a leg.",
  "When two vegans get in an argument, is it still called a beef?",
  "I ordered a chicken and an egg from Amazon. I'll let you know...",
  "Do you wanna box for your leftovers? No, but I'll wrestle you for them.",
  "That car looks nice but the muffler seems exhausted.",
  "Shout out to my fingers. I can count on all of them.",
  "If a child refuses to nap, are they guilty of resisting a rest?",
  "What country's capital is growing the fastest? Ireland. Every day it's Dublin.",
  "I once had a dream I was floating in an ocean of orange soda. It was more of a fanta sea.",
  "Did you know corduroy pillows are in style? They're making headlines.",
  "Did you hear about the kidnapping at school? It's okay, he woke up.",
  "A cheeseburger walks into a bar. The bartender says, 'Sorry, we don't serve food here.'",
  "I once got fired from a canned juice company. Apparently I couldn't concentrate.",
  "I used to play piano by ear. Now I use my hands.",
  "Have you ever tried to catch a fog? I tried yesterday but I mist.",
  "I'm on a seafood diet. I see food and I eat it.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "I made a pencil with two erasers. It was pointless.",
  "How do you make a Kleenex dance? Put a little boogie in it!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Did you hear about the guy who invented the knock-knock joke? He won the 'no-bell' prize.",
  "I've got a great joke about construction, but I'm still working on it.",
  "I used to hate facial hair...but then it grew on me.",
  "I decided to sell my vacuum cleaner—it was just gathering dust!",
  "I had a neck brace fitted years ago and I've never looked back since.",
  "You know, people say they pick their nose, but I feel like I was just born with mine.",
  "What's brown and sticky? A stick.",
  "Why can't you hear a psychiatrist using the bathroom? Because the 'P' is silent.",
  "What do you call an elephant that doesn't matter? An irrelephant.",
  "What do you get from a pampered cow? Spoiled milk.",
  "I like telling Dad jokes. Sometimes he laughs!",
  "What's the best smelling insect? A deodor-ant.",
  "I used to be a personal trainer. Then I gave my too weak notice.",
  "Did I tell you the time I fell in love during a backflip? I was heels over head!",
  "If a child refuses to sleep during nap time, are they guilty of resisting a rest?",
  "I ordered a chicken and an egg online. I’ll let you know.",
  "It takes guts to be an organ donor.",
  "If you see a crime at an Apple Store, does that make you an iWitness?",
  "I'm so good at sleeping, I can do it with my eyes closed!",
  "I was going to tell a time-traveling joke, but you guys didn't like it.",
  "What do you call a fake noodle? An impasta.",
  "What do you call a belt made of watches? A waist of time.",
  "What happens when a strawberry gets run over crossing the street? Traffic jam.",
  "What do you call two monkeys that share an Amazon account? Prime mates.",
  "What do you call a pony with a sore throat? A little hoarse.",
  "Where do math teachers go on vacation? Times Square.",
  "Whenever I try to eat healthy, a chocolate bar looks at me and Snickers.",
  "What does garlic do when it gets hot? It takes its cloves off.",
  "What's a robot's favorite snack? Computer chips.",
  "How much does it cost Santa to park his sleigh? Nothing, it's on the house.",
  "Mountains aren't just funny. They're hill areas.",
  "What do clouds wear? Thunderwear.",
  "Why are piggy banks so wise? They're filled with common cents.",
  "Why is Peter Pan always flying? He neverlands.",
  "How do you get a good price on a sled? You have toboggan.",
  "How can you tell if a tree is a dogwood tree? By its bark.",
  "I used to hate facial hair, but then it grew on me.",
  "It's inappropriate to make a 'dad joke' if you're not a dad. It's a faux pa.",
  "What do you call a hot dog on wheels? Fast food!",
  "Where do young trees go to learn? Elementree school.",
  "Did you hear about the circus fire? It was in tents.",
  "Can February March? No, but April May!",
  "How do lawyers say goodbye? We'll be suing ya!",
  "Wanna hear a joke about paper? Never mind—it's tearable.",
  "What's the best way to watch a fly fishing tournament? Live stream.",
  "Spring is here! I got so excited I wet my plants.",
  "I could tell a joke about pizza, but it's a little cheesy.",
  "Don't trust atoms. They make up everything!",
  "When does a joke become a dad joke? When it becomes apparent.",
  "I wouldn't buy anything with velcro. It's a total rip-off.",
  "What’s an astronaut’s favorite part of a computer? The space bar.",
  "I don't play soccer because I enjoy the sport. I'm just doing it for kicks!",
  "Why are elevator jokes so classic and good? They work on many levels.",
  "Why do bees have sticky hair? Because they use a honeycomb.",
  "What do you call a fake noodle? An impasta.",
  "Which state has the most streets? Rhode Island.",
  "What did the coffee report to the police? A mugging.",
  "What did the fish say when he hit the wall? Dam.",
  "Is this pool safe for diving? It deep ends.",
  "If you see a crime happen at the Apple store, what does it make you? An iWitness."
  ];
//https://www.countryliving.com/life/a27452412/best-dad-jokes/

var dict_math = [
  "Why was the math book sad? It had a lot of problems.",
  "What did the spelling book say to the math book? I know I can count on you!",
  "Why did the two fours skip lunch? They already eight!",
  "Are monsters good at math? Not unless you Count Dracula.",
  "What is the butterfly's favorite subject in school? Mothematics.",
  "How do you make time fly? Throw a clock out the window!",
  "Why is six afraid of seven? Because seven eight nine!",
  "How do you make seven even? Subtract the 'S.'",
  "Why did seven eat nine? Because you're supposed to eat 3 squared meals a day!",
  "What do you get when you multiply a New York City landmark by itself? Times Square.",
  "What do you call an adventurous number? A roamin' numeral.",
  "How are a dollar and the moon similar? They both have four quarters!",
  "Did you hear the one about the statistician? Probably.",
  "Why was the student upset when his teacher called him average? It was a mean thing to say!",
  "Why was the fraction worried about marrying the decimal? Because she would have to convert.",
  "Why is the obtuse triangle always so frustrated? Because it's never right.",
  "Why was the equal sign so humble? Because she knew she wasn't greater than or less than anyone else.",
  "What do you call a number that can't stay in one place? A Roamin' numeral.",
  "What did one math book say to the other? Don't bother me, I've got my own problems.",
  "What is a math teacher's favorite snake? A pi-thon.",
  "What do you call the number 7 and the number 3 when they go out on a date? The odd couple (but 7 is in his prime).",
  "Why was the math teacher suspicious of prime numbers? They were all odd.",
  "Why can't you trust a math teacher holding graphing paper? They must be plotting something.",
  "What is a math teacher's favorite sum? Summer.",
  "Which weighs more 16 ounces of soda or a pound of solid gold? They both weigh the same.",
  "Why did the student trust his abacus? She could always count on it.",
  "Why do plants hate math? It gives them square roots.",
  "What do you call dudes who love math? Algebros.",
  "Why should you never talk to Pi? Because she'll go on and on and on forever.",
  "Why are parallel lines so tragic? They have so much in common but they'll never meet.",
  "Dear Algebra, stop trying to find your x. They're never coming back — don't ask y.",
  "There are three kinds of people in the world: Those who can count and those who can't.",
  "How do you stay warm in any room? Just huddle in the corner, where it's always 90 degrees.",
  "Why does nobody talk to circles? Because there is no point.",
  "What do you call a tea kettle whistling on the top of a mountain? A high-pot-in-use.",
  "Did you hear about the mathematician who is afraid of negative numbers? She'd stop at nothing to avoid them.",
  "Why did the triangle make the basketball team? It always made three-pointers.",
  "Why did the kid always wear glasses during math class? They improve di-vision.",
  "What do you get when you divide the circumference of a jack-o-lantern by its diameter? Pumpkin Pi!",
  "A clerk at the butcher shop is 6 feet tall and wears size 10 shoes. What does he weigh? Meat. He works at the butcher's shop.",
  "Why can't you trust a math teacher? They're always calculating.",
  "Where did the geometry teacher go on vacation? Who knows? All I know is that she's polygon.",
  "What did the math teacher say when his parrot escaped? Polygon.",
  "What did the number eight say to zero? Nice belt.",
  "Why didn't the quarter jump off a bridge with the dime? It had more cents.",
  "What geometric shape removes spells and curses? A hexagon.",
  "Have you ever noticed what's odd? Every other whole number.",
  "What's the best tool for math? Multipliers.",
  "What's a swimmer's favorite math? Dive-ision.",
  "What do a year and a dollar have in common? They both have four quarters.",
  "What's in charge of geometry? The ruler.",
  "What's the best way to get a math tutor? An add.",
  "What's the most adventurous type of number? Roamin' numerals.",
  "What you you call an angle that's gone through the garbage disposal? A wrecked-angle.",
  "There's a fine line between a numerator and a denominator… But only a fraction would understand.",
  "What's a math teacher's favorite kind of tree? Geometry.",
  "How do you get from point A to point B? Just take an x-y plane or a rhom'bus.",
  "Why should you never mention the number 2885? Because it's 'two' gross.",
  "Why couldn't the angle get a loan? Its parents wouldn't cosine.",
  "Did you hear about the statistician who drowned crossing the river? It was 3 feet deep — on average.",
  "I'll do algebra, and I'll do trig. I'll even do statistics. But graphing is where I draw the line!",
  "What's the best way to flirt with a mathematician? Use acute angle.",
  "What do baby parabolas drink? Quadratic formula.",
  "Why did the chicken cross the Mobius Strip? To get to the same side.",
  "What's the best way to serve pi? A la mode. Anything else is mean.",
  "What do you get when you divide the circumference of the sun by its diameter? Pi in the sky.",
  "The problem with math puns is that calculus jokes are all derivative, trigonometry jokes are too graphic, algebra jokes are usually formulaic, and arithmetic jokes are pretty basic. But I guess the occasional statistics joke is an outlier.",
  "An engineer, a physicist, and a mathematician are staying in a hotel. The engineer wakes up and smells smoke. He goes out into the hallway and sees a fire, so he fills a trash can from his room with water and douses the fire. He goes back to bed. Later, the physicist wakes up and smells smoke. He opens his door and sees a fire in the hallway. He walks down the hall to a fire hose and after calculating the flame velocity, distance, water pressure, trajectory, etc., extinguishes the fire with the minimum amount of water and energy needed. Later, the mathematician wakes up and smells smoke. He goes to the hall, sees the fire and then the fire hose. He thinks for a moment and then exclaims, 'Ah, a solution exists!' and then goes back to bed.",
  "What do you call a mathematician who spent all summer at the beach? A tan gent.",
  "What do you call a political party in favor of agriculture? Pro-tractors.",
  "Why was math class so long? The teacher kept going off on a tangent.",
  "What did the zero say to the eight? Nice belt!",
  "Why do teenagers travel in groups of 3s and 5s? Because they can't even.",
  "What do you call a number that can't keep still? A roamin' numeral",
  "Why was algebra so easy for the Romans? X was always 10!",
  "What English king invented fractions? Henry the 1/8.",
  "Why didn't the hyperbola feel sick? It was asymptote-matic.",
  "I would tell you a joke about an infinite line… But it doesn't have an endpoint. Have you heard the latest stats joke? Probably…",
  "What do parallel lines and vegetarians have in common? They never meat.",
  "Why shouldn't you let advanced math intimidate you? It's easy as pi!",
  "Why did the mathematician spill all of his food in the oven? The directions said to put it in the oven at 180 degrees.",
  "Why can't you trust a polynomial to stay the same? They have too many variables.",
  "What was the geometry teacher's favorite dance? The rhombus.",
  "What do you call a 12-inch nose? A foot.",
  "Why do numerators and denominators disagree? They've drawn a line.",
  "What geometric shape is lying in wait? A trapezoid.",
  "What do you get when you add 2n to 2n in French? It sounds 4n to me, too.",
  "Did you hear about the statistician who drowned in the lake? On average, most of it was over his head.",
  "What did the triangle say to the circle? You're pointless.",
  "What do you call a student who's great at algebra? An X-pert.",
  "Three statisticians are hunting, and they come upon a deer. The first aims and overshoots. The second undershoots. The third then shouts, 'We got him!'",
  "Did you hear about the statistician who drowned? The pool was three feet deep, on average.",
  "An infinite number of mathematicians walk into a bar. The first tells the bartender he'll have a beer. The second asks for a half a beer, and the third requests a quarter. After the barman places two beers in front of all of them, they say, 'That's all you're giving us?' The bartender says, 'Come on, guys. Know your limits.'"
]; //https://www.fatherly.com/play/math-jokes-and-math-puns/
